version: '3.9'

services:
  web-api:
    container_name: web-api
    image: web-api:latest
    build: ./
    ports: 
      - "8080:5214"
    depends_on:
      - data-base

  data-base:
    image: postgres:15-alpine
    container_name: data-base
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: testDb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
volumes:
  postgres-data: